[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"


[build]
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]

[env]
ESP_LOG = "info"
